version: "3.8"

services:
  database:
    image: mysql:8.0.28
    env_file:
      - mysql.env
    ports:
      - "3306:3306"
    volumes:
      - "app_db:/var/lib/mysql"

  tika:
    image: apache/tika:2.3.0
    ports:
      - "9998:9998"

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8001:80"
    depends_on:
      - database
    links:
      - database:database
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
      - PMA_USER=admin 
      - PMA_PASSWORD=admin

volumes:
  app_db: